#!/usr/bin/env python3


def age():
  try:
    age = int(input("what is your age? " ))
    print("You are " + age + " years old!")
  except:
    
     
age()  

def helloWorld():
	print('Hello World')


helloWorld()
